# Generated by Django 5.0.7 on 2024-09-01 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Фотография')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'фотографию',
                'verbose_name_plural': 'фотография',
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'ингредиенты',
                'verbose_name_plural': 'ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Label',
                'verbose_name_plural': 'Label',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('legal_person', models.CharField(max_length=500, verbose_name='Юридическое лицо')),
                ('id_iiko', models.CharField(blank=True, help_text='Инструкция по получению: https://disk.yandex.ru/i/PZWTkEYLxv8AqA', max_length=500, verbose_name='API ключ IIKO')),
                ('org_iiko', models.CharField(blank=True, help_text='Заполняется автоматически. При необходимости используйте метод API Organizations_IIKO', max_length=500, verbose_name='ID организации IIKO')),
                ('id_chanel', models.CharField(blank=True, help_text='Инструкция по получению: https://disk.yandex.ru/d/StPnx-wW-bYKAg', max_length=500, verbose_name='ID группы Telegram для информирования')),
            ],
            options={
                'verbose_name': 'информацию о ресторане',
                'verbose_name_plural': 'информация о ресторане',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('des', models.CharField(blank=True, max_length=500, null=True, verbose_name='Рабочее поле (не заполнять)')),
                ('show', models.BooleanField(max_length=500, verbose_name='Отображение')),
                ('parrent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.category', verbose_name='ID родительской категории')),
                ('id_rest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.restaurant', verbose_name='ID ресторана')),
            ],
            options={
                'verbose_name': 'категорию меню',
                'verbose_name_plural': 'категория меню',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('weight', models.FloatField(verbose_name='Масса')),
                ('cost', models.FloatField(verbose_name='Стоимость')),
                ('cooking_time', models.CharField(max_length=500, verbose_name='Время приготовления')),
                ('kall', models.CharField(max_length=500, verbose_name='Калорийность')),
                ('show', models.BooleanField(max_length=500, verbose_name='Отображение')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.category', verbose_name='ID категории')),
                ('photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admins.foto', verbose_name='Фотогрфия')),
                ('ingredients', models.ManyToManyField(to='admins.ingredients')),
                ('label', models.ManyToManyField(to='admins.label')),
                ('id_rest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.restaurant', verbose_name='ID ресторана')),
            ],
            options={
                'verbose_name': 'блюдо',
                'verbose_name_plural': 'блюдо',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.CharField(max_length=500, verbose_name='ID стола')),
                ('total_amount', models.FloatField(blank=True, null=True, verbose_name='Сумма заказа')),
                ('dishes', models.ManyToManyField(to='admins.dish', verbose_name='Блюда')),
                ('id_rest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.restaurant', verbose_name='ID ресторана')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrator_name', models.CharField(max_length=500, verbose_name='Имя')),
                ('administrator_surname', models.CharField(max_length=500, verbose_name='Фамилия')),
                ('administrator_patronymic', models.CharField(max_length=500, verbose_name='Отчество')),
                ('status', models.CharField(help_text='На данный момент времени доступен лишь "admin"', max_length=500, verbose_name='Статус')),
                ('id_yandex', models.CharField(blank=True, max_length=500, verbose_name='ID Яндекс')),
                ('number', models.CharField(max_length=500, verbose_name='Номер телефона в формате 79051757737')),
                ('administrator_password', models.CharField(max_length=500, verbose_name='Пароль пользователя')),
                ('id_rest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.restaurant', verbose_name='ID ресторана')),
            ],
            options={
                'verbose_name': 'информацию о администраторах',
                'verbose_name_plural': 'информация о администраторах',
            },
        ),
    ]
